name = "codeine"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Principia"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Principia"
